# Generated by Django 6.0.5 on 2026-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextrainfo',
            name='role',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('vendor', 'Vendor')], max_length=10),
        ),
    ]
